### ISSUE TITLE
Guidance about the design pattern of the repo needed

### ISSUE THREAD

**Issue by akazemipour** [chanb/rl_sandbox_public#9]
Hi Bryan,
First of all congrats for the repository. Really nice and neat job! :clap: 
To some extend, I am interested in implementing SOTA RL papers as well and I have gathered all I have managed to implement [here](https://github.com/alirezakazemipour/DeepRL-Paradise).

But unlike you, I have been struggling to put them altogether in a modular manner (the same you have achieved in this repo) rather separate repositories and isolated implementations.
So, I thought to ask you if you could provide me with some tips and tricks and guidelines you followed to build up your repo?
For instance, the way you constructed an inheritance relationship between `base_policy`, `off_policy` and `on_policy` algorithms and why.

Thank you so much. :smile:

**Comment by chanb** [comment]
Hi Alireza,

Thanks for the kind words and you seem to have your own nice implementations :)
We can find some time to chat about how I designed this and what I think can be improved, perhaps a week or so from now.

**Comment by akazemipour** [comment]
That would be great Bryan!
I'm gonna be in Edmonton on Dec 17th onward and available. I'm afraid you might be on the Christmas vacations at the end of year so, If that's the case then the next term would still be fine and I can reach you again at a more convenient time of yours.
If you wanted to have an online meeting then I'm available prior to my flight. I can email you to fix a date for that.
